<?php

namespace MyApp\UserBundle\Repository;

/**
 * CentreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentreRepository extends \Doctrine\ORM\EntityRepository
{
}
