<?php

namespace MyApp\UserBundle\Repository;

/**
 * DocteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocteurRepository extends \Doctrine\ORM\EntityRepository
{
}
